# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-28 05:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0005_auto_20160528_1333'),
    ]

    operations = [
        migrations.AlterField(
            model_name='new',
            name='bigpicture',
            field=models.CharField(default=None, max_length=200),
            preserve_default=False,
        ),
    ]
