# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-28 05:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0006_auto_20160528_1346'),
    ]

    operations = [
        migrations.AlterField(
            model_name='new',
            name='bigpicture',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='new',
            name='smpicture',
            field=models.CharField(max_length=100),
        ),
    ]
