# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-28 06:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0007_auto_20160528_1347'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobcategory',
            name='index',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='new',
            name='bigpicture',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='new',
            name='smpicture',
            field=models.CharField(max_length=200),
        ),
    ]
