# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-28 06:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0008_auto_20160528_1444'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='index',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
